apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: logfile-app
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
