apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: logfile-app
spec:
  selector:
    app: kafka
  ports:
    - name: kafka-plain
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: kafka-controller
      protocol: TCP
      port: 9093
      targetPort: 9093
  type: NodePort
